### ISSUE TITLE
No "get" function in Amplifier class

### ISSUE THREAD

**Issue by teweitsai** [lsst-dm/phosim_utils#7]
I tried to repackage the amplifier the PhoSim images and got the error of no `get` attribute. It looks like there is some change in the `lsst-distrib` package of tag: `w_2019_50`.

----------------------------- Captured stderr call -----------------------------
/opt/lsst/software/stack/python/miniconda3-4.7.10/envs/lsst-scipipe-4d7b902/lib/python3.7/site-packages/astropy/config/configuration.py:532: ConfigurationMissingWarning: Configuration defaults will be used due to OSError:Could not find unix home directory to search for astropy config dir on None
  warn(ConfigurationMissingWarning(msg))
Traceback (most recent call last):
  File "/home/lsst/phosim_utils/bin/phosim_repackager.py", line 29, in <module>
    prefix=args.prefix, verbose=args.verbose)
  File "/home/lsst/phosim_utils/python/lsst/phosim/utils/phosim_repackager.py", line 85, in process_visit
    self.repackage(amp_files[sensor_id], out_dir=out_dir)
  File "/home/lsst/phosim_utils/python/lsst/phosim/utils/phosim_repackager.py", line 135, in repackage
    hdu = segments[amp.get('name')[1:]]
AttributeError: 'lsst.afw.cameraGeom.amplifier.amplifier.Amplifier' object has no attribute 'get'

**Comment by teweitsai** [comment]
Resolved in commit: 05e8eff.
